on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: install modules
      run: |
        pip3 install -U pip3
        pip3 install -U online-judge-tools

    - name: show versions
      run: |
        g++ --version
        python --version
        oj --version

    - name: run test
      run: |
        ./scripts/test.sh
